apiVersion: v2
# upstream version
appVersion: 1.22.1
name: kubeedge-cloudcore
# giantswarm chart version
version: 0.2.0
annotations:
  application.giantswarm.io/team: "rocket"
description: The KubeEdge cloudcore component.
home: https://github.com/giantswarm/kubeedge-cloudcore-app
icon: https://raw.githubusercontent.com/kubeedge/kubeedge/refs/heads/master/docs/images/kubeedge-logo-only.png
keywords:
  - edge
  - iot
  - kubernetes
maintainers:
  - name: Team Rocket
    email: team-rocket@giantswarm.io
dependencies:
  - name: kubeedge-cloudcore-crds
    version: 1.22.0
sources:
  - https://github.com/kubeedge/kubeedge
